version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
#    allowed_updates:
#      - match:
#          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"




